services:
  reminder-frontend:
    platform: linux/amd64
    build: ./frontend
    image: siegfriedschmidt/reminder-frontend
    container_name: reminder-frontend
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=10000
      - BACKEND_HOST=reminder-backend
      - BACKEND_PORT=8001
    depends_on:
      reminder-backend:
        condition: service_healthy
    networks:
      - proxy-net
      - default
    restart: unless-stopped

  reminder-backend:
    platform: linux/amd64
    build: ./backend
    image: siegfriedschmidt/reminder-backend
    container_name: reminder-backend
    environment:
      - SECRET_FOLDER_PATH=/reminder-data/secret
      - DATABASE_FOLDER_PATH=/reminder-data
      - EXPIRATION_CODE_TIME=40
      - ADMIN_EMAIL=admin@mail.ru
      - HOST=0.0.0.0
      - PORT=8001
      - TZ=Europe/Moscow
    expose:
      - "8001"
    volumes:
      - ./reminder-data:/reminder-data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8001/api/ || exit 1"
        ]
      interval: 86400s
      start_period: 10s
      start_interval: 5s
      retries: 5
    networks:
      - default
    restart: unless-stopped

  reminder-cron:
    platform: linux/amd64
    build: ./cron
    image: siegfriedschmidt/reminder-cron
    container_name: reminder-cron
    depends_on:
      reminder-backend:
        condition: service_healthy
    environment:
      - API_HOST=reminder-backend
      - API_PORT=8001
      - REGISTER_EVENTS_TIME=00:01
      - DISABLE_NOTIFICATION_TIMEOUT=10
      - SECRET_FOLDER_PATH=/reminder-data/secret
      - TZ=Europe/Moscow
    volumes:
      - ./reminder-data:/reminder-data:ro
    networks:
      - default
    restart: unless-stopped

networks:
  proxy-net:
    name: reminder-external-network
